### ISSUE TITLE
version 3.0

### ISSUE THREAD

**Issue by lprat** [Coldzer0/Cmulator#7]
Hi,

In march, you said me that you publish last version of projet (3.0) soon.
When are you publish this version?

Thanks.
Lionel

**Comment by Coldzer0** [comment]
I pushed the last update of the source code.

actually  I did wait on this because I was trying to have a decision if am gonna continue working on this or not

So I'll archive this project and I'll start a fresh base for it with C language so ppl can contribute to it.

the new project will be here https://github.com/Cmulator/Cmulator
